### ISSUE TITLE
Brow Tricks - Adding Client

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/meredith-core#245]
# Adding Client Form
BrowTricks has a collection of a tenant's clients saved with necessary client information. This issue is specifically for the "adding client" form and where that information goes within the app 
![image](https://user-images.githubusercontent.com/14948326/86566048-2a5c2100-bf93-11ea-800b-3afbb35b7c45.png)

When tenants add a new client, they add the following information: 
- First Name 
- Last Name 
- Phone Number 
- Email 
- Image Upload 
- File/PDF Upload 
![image](https://user-images.githubusercontent.com/14948326/86566069-33e58900-bf93-11ea-94ed-575cca105766.png)

There are 3 sections in the "add client" page that leads to separate pages for more complex actions 
- Notification settings (text, email, both), where the inputted phone number and email are displayed as notification options for this client. If email or phone not added, that option is not available 
![image](https://user-images.githubusercontent.com/14948326/86566162-61cacd80-bf93-11ea-9af3-af5d55d568ee.png)

- PMU Status, which leads to the PMU PDF creation process, and its preview displays complete/incomplete, based on whether PMU flow is completed. PMU PDF also gets added to "file upload" above. 
Incomplete PMU status are accepted for saving the new client, as the client may be completing the PMU form independently. 
![image](https://user-images.githubusercontent.com/14948326/86566343-b110fe00-bf93-11ea-8a01-2e80bfc0a1ec.png)

- Additional Notes are for any notes associated with this client or this client's appointments. Each entry are plain text entries. 
![image](https://user-images.githubusercontent.com/14948326/86566581-1d8bfd00-bf94-11ea-8d57-4eba059e75b6.png)

# Client List / Profile 
Added clients will be saved to the tenant's client list, and the information will be displayed on the client's profile, where tenants are able to view and edit this information, add new notes, view PMU forms, and archive (NOT DELETE) client
![image](https://user-images.githubusercontent.com/14948326/86566764-66dc4c80-bf94-11ea-9e26-294124101568.png)
![image](https://user-images.githubusercontent.com/14948326/86566809-778cc280-bf94-11ea-8e41-86d79bff2bac.png)

# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=3388%3A1997)

**You can find the designs for this issue in the "Tenant CMS" Page of Figma**

**Comment by paulchrisluke** [comment]
reviewing https://github.com/whynotearth/BrowTricks/pull/132#event-3565657410

I am unable to create a client

https://deploy-preview-132--browtricks.netlify.app/tenant/oasdioas-78/clients/add/notifications

`POST https://stagingapi.whynot.earth/api/v0/browtricks/tenant/oasdioas-78/clients 404`

response is empty, please add error messages:

![image](https://user-images.githubusercontent.com/5694308/87940846-6f6c7100-cac4-11ea-85ae-473d37638199.png)

**Comment by ctyar** [comment]
@paulchrisluke it should be fixed now

**Comment by paulchrisluke** [comment]
I'm still getting TypeError: Cannot read property '0' of null after I hit the /clients screen.

Also, whenever I try to add a user that already exists (email/number), I am unable to add that user. @ctyar @abdullahcalisir12
